version: "3.9"

services:
  redis:
    image: redis:7.0.11-alpine

  app:
    container_name: calendar_api
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./calendar_api:/calendar_api
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&  
             python manage.py runserver 0.0.0.0:8000"

    environment:
      - SECRET_KEY=dfjsklm90i4rn
      - DEBUG=1
      - ALLOWED_HOSTS=localhost,127.0.0.1
    #   - DB_HOST=
    #   - DB_NAME=
    #   - DB_USER=
    #   - DB_PASS=
    #   - DB_PORT=

    depends_on:
      - redis
      - db
    env_file:
      - .env

  db:
    image: postgres:13-alpine
    volumes:
      - dev-db-data:/var/lib/postgresql/data

    # environment:
    #   - POSTGRES_DB=devdb
    #   - POSTGRES_USER=devuser
    #   - POSTGRES_PASSWORD=changeme

    env_file:
      - .env

volumes:
  dev-db-data:
